### ISSUE TITLE
az acs kubernetes get-credentials fails with error "No authentication methods available"

### ISSUE THREAD

**Issue by DonMartin76** [Azure/ACS#22]
### Problem description

Since two months or so, we have scripts up and running which provision Kubernetes cluster on demand for testing purposes, and until today, we have always managed to get the `kubeconfig` out of the cluster via the following command line:

```
az acs kubernetes get-credentials \
    --name ${K8S_NAME} \
    --resource-group ${RESOURCE_GROUP} \
    --ssh-key-file k8sadmin.id_rsa \
    --file ./kubeconfig
```

As of today (noon or so), this fails with this error message:

```
ERROR: No authentication methods available
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/usr/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 417, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 399, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 690, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/usr/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 711, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/usr/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 48, in SecureCopy
    ssh.connect(host, username=user, pkey=pkey)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 381, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 623, in _auth
    raise SSHException('No authentication methods available')
SSHException: No authentication methods available
```

**Side note**: This is from a Linux client running inside docker; running the same directly from macOS renders a slightly different error message:

```
Authentication failed.
Traceback (most recent call last):
( ... identical to above ... )
AuthenticationException: Authentication failed.
```

When adding `--verbose --debug`, this is what gives:

```
DEBUG: paramiko.transport : Local version/idstring: SSH-2.0-paramiko_2.1.2
DEBUG: paramiko.transport : Remote version/idstring: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu1
INFO: paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
DEBUG: paramiko.transport : kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG: paramiko.transport : Kex agreed: diffie-hellman-group14-sha1
DEBUG: paramiko.transport : Cipher agreed: aes128-ctr
DEBUG: paramiko.transport : MAC agreed: hmac-sha2-256
DEBUG: paramiko.transport : Compression agreed: none
DEBUG: paramiko.transport : kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG: paramiko.transport : Switch to new keys ...
DEBUG: paramiko.transport : Adding ssh-rsa host key for dev-dev1705041406-f3d364.northeurope.cloudapp.azure.com: b945a4bc4c30a3c303138d80c015d36a
ERROR: No authentication methods available
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/usr/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 417, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 399, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 690, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/usr/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 711, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/usr/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 48, in SecureCopy
    ssh.connect(host, username=user, pkey=pkey)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 381, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 623, in _auth
    raise SSHException('No authentication methods available')
SSHException: No authentication methods available
DEBUG: paramiko.transport : EOF in transport thread
```

### Workaround

We found out we could still log in to the master VM using the `k8sadmin.id_rsa`, so it does not seem to be that we botched our key pair.

This enables the following workaround, but if there's an `az` command for it, we figured it'd be better to use that (to be sure we don't run into issues if you decide to put the `.kube/config` someplace else than on the master VM:

```
echo "INFO: Trying to scp credentials from master VM."
masterFqdn=$(az acs show --resource-group ${RESOURCE_GROUP} --name ${K8S_NAME} --query 'masterProfile.fqdn' -otsv)
echo "INFO: Master VM FQDN: ${masterFqdn}"
scp -oStrictHostKeyChecking=no -i k8sadmin.id_rsa k8sadmin@${masterFqdn}:/home/k8sadmin/.kube/config ./kubeconfig
```

Has something changed? Have we missed something, or is this a side effect from someplace else?

**Comment by JackQuincy** [comment]
So there was an update to the CLI at head to fallback to using a paramiko agent key if the default/passed in ssh key can't be loaded https://github.com/Azure/azure-cli/pull/3102 . Are you using az cli head? Is it possible your k8sadmin.id_rsa key was unreachable/unloadable? If you are using head does this repro using 2.0.4?

**Comment by DonMartin76** [comment]
This is definitely with 2.0.4, and yes, the k8sadmin.id_rsa is absolutely readable, and works; the workaround script (see above) also uses the same key, and can connect to the master via it.

```
$ az component list
[
  {
    "name": "acr",
    "version": "2.0.2"
  },
  {
    "name": "acs",
    "version": "2.0.4"
  },
  ...
]
```

**Comment by JackQuincy** [comment]
@brendandburns is it possible https://github.com/Azure/azure-cli/pull/2966 is causing this? Is Azure/azure-cli#3102 something that will fix this?

**Comment by brendandburns** [comment]
Highly likely.  @DonMartin76 can you try the tool @ head and see if this is fixed?

Thanks! (and apologies)
--brendan

**Comment by DonMartin76** [comment]
Yup, @brendandburns, can confirm it works with the HEAD version of azure-cli.

**Comment by brendandburns** [comment]
ok, closing this, apologies for the break...
