### ISSUE TITLE
Service Bus listener fails in Kubernetes ACS Custom vNet cluster

### ISSUE THREAD

**Issue by chetan3434** [Azure/ACS#73]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes , node version 1.7.5 deployed with Custom vNet

**What happened**:
I've deployed Kubernetes ACS with custom vNet.
Then implemented java spring application which reads messages from Azure Service Bus. I've referred topic listener example, https://github.com/Azure/azure-service-bus/blob/master/samples/Java/azure-servicebus/TopicClientQuickstart/src/main/java/com/microsoft/azure/servicebus/samples/topicclientquickstart/TopicClientQuickstart.java
I only updated 'maxConcurrentCalls' value to '5'.  And sent around 1000 messages in Service bus. After this when I start listener service, it just reads 10 messages from topic and stops with below error,

2017-10-16 06:21:15,432 [pool-1-thread-3] - ERROR RequestResponseLink            - RequestResponseLink open timed out.
com.microsoft.azure.servicebus.primitives.TimeoutException: Open operation on RequestResponseLink(4119ba-RequestResponse) on Entity(mytopicname/subscriptions/mysubname/$management) timed out at 2017-10-16T06:21:15.430Z[GMT].
        at com.microsoft.azure.servicebus.primitives.RequestResponseLink$1.run(RequestResponseLink.java:67)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

And same listener service code worked for 'maxConcurrentCalls' value 4.

I'm deploying service on Kubernetes in Custom vNet deployed with ACS.

I've also observed that, this **issue is only coming for K8S in custom vNet with ACS**.
Because I tried deploying same service on K8S w/o custom vNet with ACS and it worked fine with 'maxConcurrentCalls' value 10.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
- Deploy Kubernetes ACS with Custom vNet .
- Implement service bus listener with java sdk
- keep 'maxConcurrentCalls' value >4 in above listener implementation
- add ~1000 messages in service bus
- listener fails with error 'RequestResponseLink open timed out'

- And same code implementation works fine on ACS w/o custom vNet 

**Anything else we need to know**:

**Comment by chetan3434** [comment]
I've also raised an issue on Azure Service Bus github ,
https://github.com/Azure/azure-service-bus-java/issues/144
But looking at issue's behavior it only occurs in K8S ACS with Custom vNet cluster, so raising it here.
